local acceptableKeys = {
    a=true,
    b=true,
    c=true,
    d=true,
    e=true,
    f=true,
    g=true,
    h=true,
    i=true,
    j=true,
    k=true,
    l=true,
    m=true,
    n=true,
    o=true,
    p=true,
    q=true,
    r=true,
    s=true,
    t=true,
    u=true,
    v=true,
    w=true,
    x=true,
    y=true,
    z=true,
}

acceptableKeys['0'] = true
acceptableKeys['1'] = true
acceptableKeys['2'] = true
acceptableKeys['3'] = true
acceptableKeys['4'] = true
acceptableKeys['5'] = true
acceptableKeys['6'] = true
acceptableKeys['7'] = true
acceptableKeys['8'] = true
acceptableKeys['9'] = true

acceptableKeys[' '] = true
acceptableKeys['\\'] = true
acceptableKeys['|'] = true
acceptableKeys['>'] = true
acceptableKeys['<'] = true
acceptableKeys['?'] = true
acceptableKeys['/'] = true
acceptableKeys['.'] = true
acceptableKeys[','] = true
acceptableKeys['~'] = true
acceptableKeys['#'] = true
acceptableKeys['@'] = true
acceptableKeys['"'] = true
acceptableKeys['\''] = true
acceptableKeys[';'] = true
acceptableKeys[':'] = true
acceptableKeys['}'] = true
acceptableKeys['{'] = true
acceptableKeys[']'] = true
acceptableKeys['['] = true
acceptableKeys['+'] = true
acceptableKeys['_'] = true
acceptableKeys['='] = true
acceptableKeys['-'] = true
acceptableKeys[')'] = true
acceptableKeys['('] = true
acceptableKeys['*'] = true
acceptableKeys['&'] = true
acceptableKeys['^'] = true
acceptableKeys['%'] = true
acceptableKeys['$'] = true
acceptableKeys['£'] = true
acceptableKeys['!'] = true

return acceptableKeys